Fix `se-try` and `se-try-catch`
Error: `se-try` and `se-try-catch` cannot find and call a function
declared in an other scope.

Fix: Make `se-try` taking the value to test instead of the function to
call.

Other changes:
- Rename the "catch function" `$catch_func_name` to "Exception Handler"
`$handler`.
- Make `se-try-catch` taking arguments to create a custom Exception on
`false` value.
- Inform about the limitation of `se-try-catch` handler.
- Add test for the custom Exception of `se-try`.
- Change the default Exception of `se-try` message and value
- Update tests.